//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp3.TempSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TempSvc.ITempCFService")]
    public interface ITempCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITempCFService/CelciusToFarenheit", ReplyAction="http://tempuri.org/ITempCFService/CelciusToFarenheitResponse")]
        double CelciusToFarenheit(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITempCFService/CelciusToFarenheit", ReplyAction="http://tempuri.org/ITempCFService/CelciusToFarenheitResponse")]
        System.Threading.Tasks.Task<double> CelciusToFarenheitAsync(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITempCFService/FarenheitToCelcius", ReplyAction="http://tempuri.org/ITempCFService/FarenheitToCelciusResponse")]
        double FarenheitToCelcius(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITempCFService/FarenheitToCelcius", ReplyAction="http://tempuri.org/ITempCFService/FarenheitToCelciusResponse")]
        System.Threading.Tasks.Task<double> FarenheitToCelciusAsync(double value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITempCFServiceChannel : ConsoleApp3.TempSvc.ITempCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TempCFServiceClient : System.ServiceModel.ClientBase<ConsoleApp3.TempSvc.ITempCFService>, ConsoleApp3.TempSvc.ITempCFService {
        
        public TempCFServiceClient() {
        }
        
        public TempCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TempCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CelciusToFarenheit(double value) {
            return base.Channel.CelciusToFarenheit(value);
        }
        
        public System.Threading.Tasks.Task<double> CelciusToFarenheitAsync(double value) {
            return base.Channel.CelciusToFarenheitAsync(value);
        }
        
        public double FarenheitToCelcius(double value) {
            return base.Channel.FarenheitToCelcius(value);
        }
        
        public System.Threading.Tasks.Task<double> FarenheitToCelciusAsync(double value) {
            return base.Channel.FarenheitToCelciusAsync(value);
        }
    }
}
