//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int emp_no { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public string dept_no { get; set; }
    }
}
